In [1]:
from sklearn.naive_bayes import BernoulliNB
import numpy as np
import pandas as pd
import my_globals
from sklearn.model_selection import train_test_split

In [2]:
DATA_DIR = "/".join([my_globals.DATA_DIR, "features.csv"])
data = pd.read_csv(DATA_DIR)
data.head(5)

,Unnamed: 0,target,ids,date,user,text,weekday_Mon,weekday_Tue,weekday_Wed,weekday_Thu,...,tok_ðºð,tok_ð½ð,tok_ð½ñ,tok_ð¾ð,tok_ð¾ð²ð,tok_ð¾ñ,tok_øªø,tok_øªù,tok_ø³,tok_ø¹øª
0,0,4,2043910798,Fri Jun 05 08:35:39 PDT 2009,ForgottenBeauty,New blog post on 1000Markets - http://bit.ly/1...,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1,0,1982377745,Sun May 31 11:05:17 PDT 2009,jtothe9,Pink Need to buy suncream.,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2,4,2067605566,Sun Jun 07 12:38:27 PDT 2009,Paige_Leigh,Off to the park with Beebs for some frisbee an...,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,3,0,2070574930,Sun Jun 07 17:56:23 PDT 2009,Ales_Alessandra,@imbarbarella It seems that Josie had some hat...,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,4,0,2062409302,Sat Jun 06 23:09:04 PDT 2009,baldeggie,@MakikiGirl : girl I was thinking about it but...,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [3]:
features_col = [
    col for col in data.columns if (col.startswith("weekday") or col.startswith("tok") and col != "target")
]

XX = data[features_col]
yy = data[["target"]]
X_train, X_test, y_train, y_test = train_test_split(XX, yy, test_size=0.2, random_state=42)

In [4]:
from sklearn.metrics import accuracy_score
nb = BernoulliNB()
nb.fit(X_train, y_train)
y_pred = nb.predict(X_test)
print(accuracy_score(y_test, y_pred))

c:\Users\linru\Anaconda3\envs\DL\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

0.72